### ISSUE TITLE
high empty lag impact even without any node, item of own mod existing !

### ISSUE THREAD

**Issue by Festus1965** [mt-mods/pipeworks#23]
I made a test on server 5.5.0 with MTG 5.5.0 and only

last version pipeworks

on empty world, just 125 mapblocks created,
server run 10-12 hours
NO ANY item of pipepworks like tube or a injector build !!!

but /profiler save show after just 1 minute player login, extract, close

* 67.1 % / + 204 % load : [pipeworks](https://forum.minetest.net/viewtopic.php?p=408912#p408912) via ... [github.com/mt-mods/pipeworks](https://github.com/mt-mods/pipeworks) with basic_materials - tested

data here: https://forum.minetest.net/viewtopic.php?p=408753#p408753

HOW can this be ?

I am near to call it lag mod, as it works even no items/node of its own to work with.

**Comment by Festus1965** [comment]
to compare with techage:
* pipeworks with technic rises up 75.6 %
* techage only 30.4 %
* terumet by 0% - that is how it should be, when no node is build yet.

**Comment by S-S-X** [comment]
This seems to be already solved by "switch to techage", thanks for suggestions.

**Comment by BuckarooBanzay** [comment]
@Festus1965 just fyi: i blocked you from this org because you aren't really constructive.
Basically all you do is complain without ever providing solutions or ideas (this isn't the only place you are doing this).
IMO: I think we are all better off in this org when we don't have to attend to your "comments"

Anyhow: if you are still interested in this community and learn to express yourself better feel free to appeal in the IRC-channel or discord.

Have a nice day
