### ISSUE TITLE
[BUG][Visual] Stray items

### ISSUE THREAD

**Issue by Monniasza** [mt-mods/pipeworks#77]
In certain pipe setups, items can show originating outside of pipes, not just overshooting. Overshooting is visible too.

https://github.com/mt-mods/pipeworks/assets/37037712/8e63e40b-123b-4e66-a09f-36ed735904c5

**Comment by Niklp09** [comment]
That's due to serverlag.

**Comment by S-S-X** [comment]
Or whatever lag that causes client to not receive new velocity/direction/location for entities.

Reason is basically that when items move (visually) server just sends item position, direction and velocity to your client.
Then item keeps going that way on your screen until you get update from server telling to change direction of item / velocity of item / remove item / change something else.

In other words: item isn't necessarily really where you see it but you just do not know any better yet because you only had its starting position, velocity and direction but not information about how long or how far it should move.

(maybe it could actually be done using particles instead of entities as particles can have client side life time and therefore distance in addition to start pos, velocity and direction)

**Comment by BuckarooBanzay** [comment]
> That's due to serverlag.

basically this ^ does not matter how much optimizations are done in regard to item-transport, server-lag will always cause this, sorry :/

> (maybe it could actually be done using particles instead of entities as particles can have client side life time and therefore distance in addition to start pos, velocity and direction)

sounds interesting but iirc particles don't have a "cube" visual
